"""Agent Reach's additive structured execution protocol v1."""

from .contracts import (
    EXECUTION_ERROR_CODES,
    FETCHED_DOCUMENT_CAPABILITY,
    LINKEDIN_MCP_CAPABILITY,
    MCPORTER_ARTIFACTS_CAPABILITY,
    NETWORK_ACCESS_CAPABILITY,
    OPENCLI_SESSION_CAPABILITY,
    PRIVATE_WORKSPACE_CAPABILITY,
    PROTOCOL_VERSION,
    XUEQIU_SESSION_CAPABILITY,
    ExecutionContextV1,
    ExecutionErrorCodeV1,
    ExecutionFailureV1,
    ExecutionItemV1,
    ExecutionLimitsV1,
    ExecutionRequestV1,
    ExecutionResultV1,
    ExecutionSuccessV1,
    FetchedDocumentV1,
    LinkedInMcpV1,
    McporterArtifactsV1,
    NetworkAccessV1,
    OpenCliSessionV1,
    OperationCapabilityV1,
    PrivateWorkspaceV1,
    XueqiuSessionV1,
)
from .registry import execute, list_capabilities

__all__ = [
    "EXECUTION_ERROR_CODES",
    "FETCHED_DOCUMENT_CAPABILITY",
    "LINKEDIN_MCP_CAPABILITY",
    "MCPORTER_ARTIFACTS_CAPABILITY",
    "NETWORK_ACCESS_CAPABILITY",
    "OPENCLI_SESSION_CAPABILITY",
    "PRIVATE_WORKSPACE_CAPABILITY",
    "PROTOCOL_VERSION",
    "XUEQIU_SESSION_CAPABILITY",
    "ExecutionContextV1",
    "ExecutionErrorCodeV1",
    "ExecutionFailureV1",
    "ExecutionItemV1",
    "ExecutionLimitsV1",
    "ExecutionRequestV1",
    "ExecutionResultV1",
    "ExecutionSuccessV1",
    "FetchedDocumentV1",
    "LinkedInMcpV1",
    "McporterArtifactsV1",
    "NetworkAccessV1",
    "OpenCliSessionV1",
    "OperationCapabilityV1",
    "PrivateWorkspaceV1",
    "XueqiuSessionV1",
    "execute",
    "list_capabilities",
]
